/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/members/mypage': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 마이페이지 조회
     * @description 마이페이지에서 유저 정보를 조회합니다.
     */
    get: operations['getMypage'];
    /**
     * 마이페이지 수정
     * @description 마이페이지에서 유저 프로필을 수정합니다.
     */
    put: operations['updateMypage'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v2/members/onboard': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 회원 온보딩 V2
     * @description PENDING 상태의 회원의 온보딩 결과를 저장합니다.
     */
    post: operations['onboardMember'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/rag/required': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 필수 참고 문서 업로드 (Server Only)
     * @description 로드맵 생성 시 반드시 참고해야 하는 문서를 업로드합니다.
     */
    post: operations['uploadRequired'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/rag/policy': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 정책 PDF 문서 업로드 (Server Only)
     * @description 정책 관련 PDF 문서를 임베딩하여 vectorDB에 저장합니다.
     */
    post: operations['uploadPolicyFile'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/rag/job-posting': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 채용 공고 임베딩 (Server Only)
     * @description 채용 공고 정보를 임베딩하여 vectorDB에 저장합니다.
     */
    post: operations['uploadJobPosting'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/phase-actions/{phaseActionId}/todo': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Phase Action 기반 Todo 생성
     * @description 특정 Phase Action을 기반으로 Todo를 생성합니다.
     */
    post: operations['createPhaseActionTodo'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/members/term-agreements': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 약관 동의
     * @description 약관에 동의합니다.
     */
    post: operations['agreeTerms'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/members/roadmap': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * AI 로드맵 생성 API
     * @description 사용자가 온보딩에 입력한 정보를 통해 로드맵을 생성합니다.
     */
    post: operations['generateRoadmap'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/members/roadmap/test': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * AI 로드맵 생성 테스트용 API (Server Only)
     * @description 사용자가 온보딩에 입력한 정보를 통해 로드맵을 생성합니다.
     */
    post: operations['generateRoadmapForTest'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/members/onboard': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 회원 온보딩
     * @description PENDING 상태의 회원의 온보딩 결과를 저장합니다.
     */
    post: operations['onboardMember_1'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/members/onboard/ocr/visa': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 온보딩 비자 OCR API
     * @description 온보딩 과정에서 유저의 비자 문서를 분석하여 정보를 추출합니다.
     */
    post: operations['getVisaInfo'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/members/onboard/ocr/passport': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 온보딩 여권 OCR API
     * @description 온보딩 과정에서 유저의 여권을 분석하여 정보를 추출합니다.
     */
    post: operations['getPassportInfo'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/job-postings/{jobPostingId}/bookmarks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 채용 공고 북마크 추가/삭제
     * @description 사용자가 추천된 채용 공고를 추가하거나 삭제합니다.
     */
    post: operations['createJobPostingBookmark'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/job-postings/recommend': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 채용 공고 추천
     * @description 사용자가 업로드한 이력서/자소서, 사용자 정보 기반으로 채용 공고를 추천합니다.
     */
    post: operations['recommendJobPostings'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/sign-out': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 로그아웃
     * @description Refresh Token 쿠키를 삭제하고 Access Token을 블랙리스트에 등록합니다.
     */
    post: operations['signOut'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/reissue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 토큰 재발급
     * @description Refresh Token 쿠키를 이용해 Access Token을 재발급합니다.
     */
    post: operations['reissue'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/code/exchange': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 로그인 코드 교환
     * @description OAuth 로그인 후 발급된 임시 코드를 AT/RT로 교환합니다.
     */
    post: operations['exchange'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/action-items/{actionItemId}/completed': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * 액션 아이템 완료 상태 토글
     * @description 특정 액션 아이템의 완료 상태를 토글합니다.
     */
    patch: operations['toggleActionItemCompletion'];
    trace?: never;
  };
  '/api/v1/terms': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 약관 조회
     * @description 약관 내용을 조회합니다.
     */
    get: operations['getTerms'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/phases': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Phase 리스트 조회
     * @description Phase 리스트를 조회합니다.
     */
    get: operations['getPhaseList'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/phases/{phaseId}/roadmap': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 로드맵 Phase 상세정보 조회
     * @description 로드맵 Phase 상세조회를 조회합니다.
     */
    get: operations['getRoadmapPhaseDetail'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/phases/{phaseId}/home': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 홈 Phase 상세정보 조회
     * @description 홈 Phase 상세조회를 조회합니다.
     */
    get: operations['getHomePhaseDetail'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/phase-actions/{phaseActionId}/guide': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * AI 가이드 조회
     * @description AI 가이드를 조회합니다.
     */
    get: operations['getAiGuide'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/members/onboard/universities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 온보딩 대학교 목록 조회
     * @description 회원 온보딩 시 선택할 수 있는 대학교 목록을 조회합니다.
     */
    get: operations['getOnboardUniversities'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/members/onboard/majors': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 온보딩 전공 목록 조회
     * @description 회원 온보딩 시 선택할 수 있는 전공 목록을 조회합니다.
     */
    get: operations['getOnboardMajors'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/members/onboard/fields': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 온보딩 관심 분야 목록 조회
     * @description 회원 온보딩 시 선택할 수 있는 관심 분야 목록을 조회합니다.
     */
    get: operations['getOnboardFields'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/members/onboard/countries': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 온보딩 국가 목록 조회
     * @description 회원 온보딩 시 선택할 수 있는 국가 목록을 조회합니다.
     */
    get: operations['getOnboardCountries'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/members/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 회원 정보 조회
     * @description 로그인한 회원의 정보를 조회합니다.
     */
    get: operations['getMemberInfo'];
    put?: never;
    post?: never;
    /**
     * 회원 탈퇴
     * @description 회원 탈퇴를 진행합니다.
     */
    delete: operations['deleteMember'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/members/me/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 유저 상태 조회
     * @description 사용자의 비자 정보, 졸업 정보를 조회합니다.
     */
    get: operations['getMemberStatus'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/job-postings/crawl': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 채용 공고 크롤링 (Server Only) */
    get: operations['crawlJobPostings'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/job-postings/bookmarks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 채용 공고 북마크 조회
     * @description 사용자가 북마크한 채용 공고를 조회합니다.
     */
    get: operations['getJobPostingBookmarks'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/action-items': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 액션 아이템 전체 조회
     * @description 로그인한 회원의 활성화된 모든 액션 아이템을 조회합니다.
     */
    get: operations['getAllActionItems'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    BaseErrorResponse: {
      /** Format: int32 */
      code?: number;
      message?: string;
      messageDetail?: string;
    };
    MypageRequest: {
      /**
       * @description 목표 직무
       * @example Developer
       */
      targetJob: string;
      /**
       * Format: date
       * @description 생년월일
       */
      birthDate: string;
      /**
       * @description 국가
       * @example Afghanistan
       */
      countryCode: string;
      /**
       * @description 학위
       * @example DOMESTIC_ASSOCIATE
       * @enum {string}
       */
      degree:
        | 'DOMESTIC_ASSOCIATE'
        | 'DOMESTIC_BACHELORS'
        | 'DOMESTIC_MASTERS'
        | 'DOMESTIC_DOCTORATE'
        | 'OVERSEAS_BACHELORS'
        | 'OVERSEAS_MASTERS'
        | 'OVERSEAS_DOCTORATE';
      /**
       * @description 대학
       * @example Konkuk University
       */
      universityCode: string;
      /**
       * @description 전공
       * @example Computer Science
       */
      primaryMajorCode: string;
      /**
       * @description 부전공
       * @example Statistic
       */
      secondaryMajor: string;
      /**
       * @description 비자 유형
       * @example D2
       * @enum {string}
       */
      visaType: 'D2' | 'D10' | 'E7';
      /**
       * Format: date
       * @description 비자 만료일
       * @example 2027-01-01
       */
      visaExpiredAt: string;
      /**
       * @description 언어 수준
       * @example LEVEL_3
       * @enum {string}
       */
      languageLevel:
        | 'LEVEL_1'
        | 'LEVEL_2'
        | 'LEVEL_3'
        | 'LEVEL_4'
        | 'LEVEL_5'
        | 'NOT_TAKEN';
      /**
       * @description 영어 실력
       * @example BEGINNER
       * @enum {string}
       */
      englishLevel: 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED';
    };
    BaseResponseVoid: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: Record<string, never>;
    };
    MemberOnboardV2Request: {
      name: string;
      /** Format: date */
      birthDate: string;
      universityCode: string;
      countryCode: string;
      /** @enum {string} */
      languageLevel:
        | 'LEVEL_1'
        | 'LEVEL_2'
        | 'LEVEL_3'
        | 'LEVEL_4'
        | 'LEVEL_5'
        | 'NOT_TAKEN';
      /** @enum {string} */
      englishLevel: 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED';
      /** @enum {string} */
      degree:
        | 'DOMESTIC_ASSOCIATE'
        | 'DOMESTIC_BACHELORS'
        | 'DOMESTIC_MASTERS'
        | 'DOMESTIC_DOCTORATE'
        | 'OVERSEAS_BACHELORS'
        | 'OVERSEAS_MASTERS'
        | 'OVERSEAS_DOCTORATE';
      /** @enum {string} */
      visaType: 'D2' | 'D10' | 'E7';
      /**
       * Format: date
       * @description 예상 졸업일, D2 비자인 경우만
       * @example 2025-08-31
       */
      expectedGraduationDate?: string;
      /** Format: date */
      visaStartDate: string;
      /** Format: date */
      visaExpiredAt: string;
      primaryMajorCode: string;
      secondaryMajor?: string;
      fieldsOfInterests: string[];
      preparationStatuses?: string[];
      targetJob: string;
      targetJobSkill?: string;
      personalBackground: string;
    };
    JobPostingEmbeddingRequest: {
      jobPostingIds?: number[];
    };
    /** @description 약관 동의 요청 */
    MemberTermsRequest: {
      /** @description 약관 동의 리스트 */
      agreements: components['schemas']['TermAgreement'][];
    };
    /** @description 약관 동의 리스트 */
    TermAgreement: {
      /**
       * Format: int64
       * @description 약관 고유번호
       * @example 1
       */
      termId: number;
      /**
       * @description 약관 동의여부
       * @example true
       */
      agreed: boolean;
    };
    ActionItemPlan: {
      title?: string;
      actionsType?: string;
      deadline?: string;
    };
    BaseResponseRoadmapTestResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['RoadmapTestResponse'];
    };
    PhaseActionPlan: {
      title?: string;
      description?: string;
      type?: string;
      deadline?: string;
      importance?: string;
      guideline?: string[];
      commonMistakes?: string[];
      actionItems?: components['schemas']['ActionItemPlan'][];
    };
    PhasePlan: {
      status?: string;
      /** Format: int32 */
      sequence?: number;
      goal?: string;
      description?: string;
      startDate?: string;
      endDate?: string;
      actions?: components['schemas']['PhaseActionPlan'][];
    };
    RetrievedChunk: {
      /** Format: int32 */
      index?: number;
      textPreview?: string;
      metadata?: {
        [key: string]: Record<string, never>;
      };
    };
    RoadmapResponse: {
      phases?: components['schemas']['PhasePlan'][];
    };
    RoadmapTestResponse: {
      roadmap?: components['schemas']['RoadmapResponse'];
      retrieved?: components['schemas']['RetrievedChunk'][];
    };
    MemberOnboardRequest: {
      name: string;
      /** Format: date */
      birthDate: string;
      /** @enum {string} */
      country:
        | 'Afghanistan'
        | 'Albania'
        | 'Algeria'
        | 'Andorra'
        | 'Angola'
        | 'Antigua and Barbuda'
        | 'Argentina'
        | 'Armenia'
        | 'Australia'
        | 'Austria'
        | 'Azerbaijan'
        | 'Bahamas'
        | 'Bahrain'
        | 'Bangladesh'
        | 'Barbados'
        | 'Belarus'
        | 'Belgium'
        | 'Belize'
        | 'Benin'
        | 'Bhutan'
        | 'Bolivia'
        | 'Bosnia and Herzegovina'
        | 'Botswana'
        | 'Brazil'
        | 'Brunei'
        | 'Bulgaria'
        | 'Burkina Faso'
        | 'Burundi'
        | 'Cabo Verde'
        | 'Cambodia'
        | 'Cameroon'
        | 'Canada'
        | 'Central African Republic'
        | 'Chad'
        | 'Chile'
        | 'China'
        | 'Colombia'
        | 'Comoros'
        | 'Congo'
        | 'Democratic Republic of the Congo'
        | 'Costa Rica'
        | "Cote d'Ivoire"
        | 'Croatia'
        | 'Cuba'
        | 'Cyprus'
        | 'Czechia'
        | 'Denmark'
        | 'Djibouti'
        | 'Dominica'
        | 'Dominican Republic'
        | 'Ecuador'
        | 'Egypt'
        | 'El Salvador'
        | 'Equatorial Guinea'
        | 'Eritrea'
        | 'Estonia'
        | 'Eswatini'
        | 'Ethiopia'
        | 'Fiji'
        | 'Finland'
        | 'France'
        | 'Gabon'
        | 'Gambia'
        | 'Georgia'
        | 'Germany'
        | 'Ghana'
        | 'Greece'
        | 'Grenada'
        | 'Guatemala'
        | 'Guinea'
        | 'Guinea-Bissau'
        | 'Guyana'
        | 'Haiti'
        | 'Honduras'
        | 'Hungary'
        | 'Iceland'
        | 'India'
        | 'Indonesia'
        | 'Iran'
        | 'Iraq'
        | 'Ireland'
        | 'Israel'
        | 'Italy'
        | 'Jamaica'
        | 'Japan'
        | 'Jordan'
        | 'Kazakhstan'
        | 'Kenya'
        | 'Kiribati'
        | 'Kuwait'
        | 'Kyrgyzstan'
        | 'Laos'
        | 'Latvia'
        | 'Lebanon'
        | 'Lesotho'
        | 'Liberia'
        | 'Libya'
        | 'Liechtenstein'
        | 'Lithuania'
        | 'Luxembourg'
        | 'Madagascar'
        | 'Malawi'
        | 'Malaysia'
        | 'Maldives'
        | 'Mali'
        | 'Malta'
        | 'Marshall Islands'
        | 'Mauritania'
        | 'Mauritius'
        | 'Mexico'
        | 'Micronesia'
        | 'Moldova'
        | 'Monaco'
        | 'Mongolia'
        | 'Montenegro'
        | 'Morocco'
        | 'Mozambique'
        | 'Myanmar'
        | 'Namibia'
        | 'Nauru'
        | 'Nepal'
        | 'Netherlands'
        | 'New Zealand'
        | 'Nicaragua'
        | 'Niger'
        | 'Nigeria'
        | 'North Macedonia'
        | 'Norway'
        | 'Oman'
        | 'Pakistan'
        | 'Palau'
        | 'Panama'
        | 'Papua New Guinea'
        | 'Paraguay'
        | 'Peru'
        | 'Philippines'
        | 'Poland'
        | 'Portugal'
        | 'Qatar'
        | 'Romania'
        | 'Russia'
        | 'Rwanda'
        | 'Saint Kitts and Nevis'
        | 'Saint Lucia'
        | 'Saint Vincent and the Grenadines'
        | 'Samoa'
        | 'San Marino'
        | 'Sao Tome and Principe'
        | 'Saudi Arabia'
        | 'Senegal'
        | 'Serbia'
        | 'Seychelles'
        | 'Sierra Leone'
        | 'Singapore'
        | 'Slovakia'
        | 'Slovenia'
        | 'Solomon Islands'
        | 'Somalia'
        | 'South Africa'
        | 'South Korea'
        | 'South Sudan'
        | 'Spain'
        | 'Sri Lanka'
        | 'Sudan'
        | 'Suriname'
        | 'Sweden'
        | 'Switzerland'
        | 'Syria'
        | 'Taiwan'
        | 'Tajikistan'
        | 'Tanzania'
        | 'Thailand'
        | 'Timor-Leste'
        | 'Togo'
        | 'Tonga'
        | 'Trinidad and Tobago'
        | 'Tunisia'
        | 'Turkey'
        | 'Turkmenistan'
        | 'Tuvalu'
        | 'Uganda'
        | 'Ukraine'
        | 'United Arab Emirates'
        | 'United Kingdom'
        | 'United States'
        | 'Uruguay'
        | 'Uzbekistan'
        | 'Vanuatu'
        | 'Vatican City'
        | 'Venezuela'
        | 'Vietnam'
        | 'Yemen'
        | 'Zambia'
        | 'Zimbabwe';
      /** @enum {string} */
      languageLevel:
        | 'LEVEL_1'
        | 'LEVEL_2'
        | 'LEVEL_3'
        | 'LEVEL_4'
        | 'LEVEL_5'
        | 'NOT_TAKEN';
      /** @enum {string} */
      degree:
        | 'DOMESTIC_ASSOCIATE'
        | 'DOMESTIC_BACHELORS'
        | 'DOMESTIC_MASTERS'
        | 'DOMESTIC_DOCTORATE'
        | 'OVERSEAS_BACHELORS'
        | 'OVERSEAS_MASTERS'
        | 'OVERSEAS_DOCTORATE';
      /** @enum {string} */
      visaType: 'D2' | 'D10' | 'E7';
      /**
       * Format: date
       * @description 예상 졸업일, D2 비자인 경우만
       * @example 2025-08-31
       */
      expectedGraduationDate?: string;
      /** Format: date */
      visaStartDate: string;
      /** Format: date */
      visaExpiredAt: string;
      /**
       * Format: int32
       * @description 비자 점수, D10 비자인 경우만
       * @example 50
       */
      visaPoint?: number;
      primaryMajor: string;
      secondaryMajor?: string;
      targetJob: string;
      targetJobSkill?: string;
      personalBackground: string;
    };
    BaseResponseOcrVisaResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['OcrVisaResponse'];
    };
    OcrVisaResponse: {
      /**
       * @description 비자 유형
       * @enum {string}
       */
      visaType?: 'D2' | 'D10' | 'E7';
      /**
       * Format: date
       * @description 비자 발급일
       */
      visaStartDate?: string;
      /**
       * Format: date
       * @description 비자 만료일
       */
      visaExpiredAt?: string;
    };
    BaseResponseOcrPassportResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['OcrPassportResponse'];
    };
    OcrPassportResponse: {
      /**
       * @description Full Name
       * @example Hong Seungwon
       */
      fullName?: string;
      /**
       * @description 국가
       * @example AFGHANISTAN
       * @enum {string}
       */
      country?:
        | 'Afghanistan'
        | 'Albania'
        | 'Algeria'
        | 'Andorra'
        | 'Angola'
        | 'Antigua and Barbuda'
        | 'Argentina'
        | 'Armenia'
        | 'Australia'
        | 'Austria'
        | 'Azerbaijan'
        | 'Bahamas'
        | 'Bahrain'
        | 'Bangladesh'
        | 'Barbados'
        | 'Belarus'
        | 'Belgium'
        | 'Belize'
        | 'Benin'
        | 'Bhutan'
        | 'Bolivia'
        | 'Bosnia and Herzegovina'
        | 'Botswana'
        | 'Brazil'
        | 'Brunei'
        | 'Bulgaria'
        | 'Burkina Faso'
        | 'Burundi'
        | 'Cabo Verde'
        | 'Cambodia'
        | 'Cameroon'
        | 'Canada'
        | 'Central African Republic'
        | 'Chad'
        | 'Chile'
        | 'China'
        | 'Colombia'
        | 'Comoros'
        | 'Congo'
        | 'Democratic Republic of the Congo'
        | 'Costa Rica'
        | "Cote d'Ivoire"
        | 'Croatia'
        | 'Cuba'
        | 'Cyprus'
        | 'Czechia'
        | 'Denmark'
        | 'Djibouti'
        | 'Dominica'
        | 'Dominican Republic'
        | 'Ecuador'
        | 'Egypt'
        | 'El Salvador'
        | 'Equatorial Guinea'
        | 'Eritrea'
        | 'Estonia'
        | 'Eswatini'
        | 'Ethiopia'
        | 'Fiji'
        | 'Finland'
        | 'France'
        | 'Gabon'
        | 'Gambia'
        | 'Georgia'
        | 'Germany'
        | 'Ghana'
        | 'Greece'
        | 'Grenada'
        | 'Guatemala'
        | 'Guinea'
        | 'Guinea-Bissau'
        | 'Guyana'
        | 'Haiti'
        | 'Honduras'
        | 'Hungary'
        | 'Iceland'
        | 'India'
        | 'Indonesia'
        | 'Iran'
        | 'Iraq'
        | 'Ireland'
        | 'Israel'
        | 'Italy'
        | 'Jamaica'
        | 'Japan'
        | 'Jordan'
        | 'Kazakhstan'
        | 'Kenya'
        | 'Kiribati'
        | 'Kuwait'
        | 'Kyrgyzstan'
        | 'Laos'
        | 'Latvia'
        | 'Lebanon'
        | 'Lesotho'
        | 'Liberia'
        | 'Libya'
        | 'Liechtenstein'
        | 'Lithuania'
        | 'Luxembourg'
        | 'Madagascar'
        | 'Malawi'
        | 'Malaysia'
        | 'Maldives'
        | 'Mali'
        | 'Malta'
        | 'Marshall Islands'
        | 'Mauritania'
        | 'Mauritius'
        | 'Mexico'
        | 'Micronesia'
        | 'Moldova'
        | 'Monaco'
        | 'Mongolia'
        | 'Montenegro'
        | 'Morocco'
        | 'Mozambique'
        | 'Myanmar'
        | 'Namibia'
        | 'Nauru'
        | 'Nepal'
        | 'Netherlands'
        | 'New Zealand'
        | 'Nicaragua'
        | 'Niger'
        | 'Nigeria'
        | 'North Macedonia'
        | 'Norway'
        | 'Oman'
        | 'Pakistan'
        | 'Palau'
        | 'Panama'
        | 'Papua New Guinea'
        | 'Paraguay'
        | 'Peru'
        | 'Philippines'
        | 'Poland'
        | 'Portugal'
        | 'Qatar'
        | 'Romania'
        | 'Russia'
        | 'Rwanda'
        | 'Saint Kitts and Nevis'
        | 'Saint Lucia'
        | 'Saint Vincent and the Grenadines'
        | 'Samoa'
        | 'San Marino'
        | 'Sao Tome and Principe'
        | 'Saudi Arabia'
        | 'Senegal'
        | 'Serbia'
        | 'Seychelles'
        | 'Sierra Leone'
        | 'Singapore'
        | 'Slovakia'
        | 'Slovenia'
        | 'Solomon Islands'
        | 'Somalia'
        | 'South Africa'
        | 'South Korea'
        | 'South Sudan'
        | 'Spain'
        | 'Sri Lanka'
        | 'Sudan'
        | 'Suriname'
        | 'Sweden'
        | 'Switzerland'
        | 'Syria'
        | 'Taiwan'
        | 'Tajikistan'
        | 'Tanzania'
        | 'Thailand'
        | 'Timor-Leste'
        | 'Togo'
        | 'Tonga'
        | 'Trinidad and Tobago'
        | 'Tunisia'
        | 'Turkey'
        | 'Turkmenistan'
        | 'Tuvalu'
        | 'Uganda'
        | 'Ukraine'
        | 'United Arab Emirates'
        | 'United Kingdom'
        | 'United States'
        | 'Uruguay'
        | 'Uzbekistan'
        | 'Vanuatu'
        | 'Vatican City'
        | 'Venezuela'
        | 'Vietnam'
        | 'Yemen'
        | 'Zambia'
        | 'Zimbabwe';
      /**
       * Format: date
       * @description 생년월일
       */
      birthDate?: string;
    };
    BaseResponseJobPostingListResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['JobPostingListResponse'];
    };
    JobPostingListResponse: {
      jobPostingResponses?: components['schemas']['JobPostingResponse'][];
    };
    JobPostingResponse: {
      /**
       * Format: int64
       * @description 채용 공고 ID
       * @example 1
       */
      jobPostingId?: number;
      /**
       * Format: date
       * @description 마감일
       */
      deadline?: string;
      /** @description 이미지 url */
      imageUrl?: string;
      /**
       * @description 회사명
       * @example THEIA
       */
      company?: string;
      /**
       * @description 채용 공고 제목
       * @example Hiring Japanese Marketers
       */
      title?: string;
      /**
       * @description 근무 형태
       * @example Part-time Worker
       */
      arrangement?: string[];
      /** @description 주소 */
      address?: string[];
      /** @description 공고 url */
      websiteUrl?: string;
      /** @description 북마크 여부 */
      isBookmarked?: boolean;
    };
    BaseResponseTokenResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['TokenResponse'];
    };
    TokenResponse: {
      accessToken?: string;
    };
    TokenExchangeRequest: {
      code: string;
    };
    BaseResponseTokenExchangeResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['TokenExchangeResponse'];
    };
    TokenExchangeResponse: {
      accessToken?: string;
      onboardingRequired?: boolean;
    };
    BaseResponseTermsResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['TermsResponse'];
    };
    /** @description 약관 리스트 */
    TermResponse: {
      /**
       * Format: int64
       * @description 약관 고유번호
       * @example 1
       */
      termId?: number;
      /**
       * @description 약관 제목
       * @example Terms of Service
       */
      title?: string;
      /**
       * @description 약관 내용
       * @example 1. Purpose ~
       */
      content?: string;
      /**
       * @description 필수 여부
       * @example true
       */
      required?: boolean;
    };
    /** @description 약관 응답 */
    TermsResponse: {
      /** @description 약관 리스트 */
      terms?: components['schemas']['TermResponse'][];
    };
    BaseResponsePhaseListResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['PhaseListResponse'];
    };
    /** @description Phase 리스트 응답 */
    PhaseListResponse: {
      /** @description Phase 리스트 응답 */
      phases?: components['schemas']['PhaseResponse'][];
    };
    /** @description Phase 리스트 아이템 응답 */
    PhaseResponse: {
      /**
       * Format: int64
       * @description Phase id
       * @example 1
       */
      phaseId?: number;
      /**
       * @description Phase 상태
       * @example Current
       */
      phaseStatus?: string;
      /**
       * Format: int32
       * @description Phase 순서
       * @example 1
       */
      sequence?: number;
      /**
       * @description Phase 목표
       * @example Verify Requirements
       */
      goal?: string;
      /**
       * @description Phase 설명
       * @example Initial setup and documentation
       */
      description?: string;
      /**
       * @description Work 상태
       * @example Remained works
       */
      workStatus?: string;
      /**
       * Format: int64
       * @description Work 수(Phase 상태에 따라 남은 work 수, 계획된 work 수)
       * @example 3
       */
      worksCount?: number;
      /**
       * Format: date
       * @description Phase 시작일
       * @example 2025-09-01
       */
      startDate?: string;
      /**
       * Format: date
       * @description Phase 종료일
       * @example 2025-12-01
       */
      endDate?: string;
    };
    /** @description Phase에 해당하는 그룹화된 PhaseAction */
    ActionGroupResponse: {
      /**
       * Format: int64
       * @description 태그(Visa, Career, Done)에 해당하는 PhaseAction 수
       * @example 1
       */
      count?: number;
      /** @description 태그(Visa, Career, Done)에 해당하는 PhaseAction 리스트 */
      items?: components['schemas']['ActionResponse'][];
    };
    /** @description 태그(Visa, Career, Done)에 해당하는 PhaseAction 리스트 */
    ActionResponse: {
      /**
       * Format: int64
       * @description Phase Action 고유번호
       * @example 1
       */
      phaseActionId?: number;
      /**
       * @description Phase Action 제목
       * @example Prepare internship log
       */
      title?: string;
      /**
       * @description Phase Action 설명
       * @example Document all work experience during internship period
       */
      description?: string;
      /**
       * Format: date
       * @description Phase Action 마감 기한
       * @example 2026-01-24
       */
      deadline?: string;
      /**
       * @description Phase Action todo 추가 여부
       * @example true
       */
      added?: boolean;
    };
    BaseResponseRoadmapPhaseDetailResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['RoadmapPhaseDetailResponse'];
    };
    /** @description 로드맵 Phase 상세 조회 응답 */
    RoadmapPhaseDetailResponse: {
      /**
       * Format: int64
       * @description Phase의 PhaseAction 수
       * @example 1
       */
      totalCount?: number;
      /** @description Phase에 해당하는 그룹화된 PhaseAction */
      actions?: {
        [key: string]: components['schemas']['ActionGroupResponse'];
      };
    };
    BaseResponseHomePhaseDetailResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['HomePhaseDetailResponse'];
    };
    /** @description Phase의 PhaseAction 리스트 */
    HomePhaseActionResponse: {
      /**
       * Format: int64
       * @description Phase Action 고유번호
       * @example 1
       */
      phaseActionId?: number;
      /**
       * @description Phase Action 타입
       * @example Visa
       */
      type?: string;
      /**
       * @description Phase Action 제목
       * @example Prepare OPT application documents
       */
      title?: string;
      /**
       * Format: date
       * @description Phase Action 마감기한
       * @example 2026-01-01
       */
      deadline?: string;
    };
    /** @description 홈 Phase 리스트 조회 응답 */
    HomePhaseDetailResponse: {
      /**
       * Format: int64
       * @description Phase의 PhaseAction 수
       * @example 1
       */
      count?: number;
      /** @description Phase의 PhaseAction 리스트 */
      actions?: components['schemas']['HomePhaseActionResponse'][];
    };
    /** @description AI 가이드 응답 */
    AiGuideResponse: {
      /** @description AI guide - Why this matters */
      importance?: string;
      /** @description AI guide - How to do it properly */
      mistakes?: string[];
      /** @description AI guide - Common mistakes */
      guidelines?: string[];
    };
    BaseResponseAiGuideResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['AiGuideResponse'];
    };
    BaseResponseOnboardUniversitiesResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['OnboardUniversitiesResponse'];
    };
    LocalizedItemResponse: {
      code?: string;
      label?: string;
    };
    OnboardUniversitiesResponse: {
      universities?: components['schemas']['LocalizedItemResponse'][];
    };
    BaseResponseOnboardMajorsResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['OnboardMajorsResponse'];
    };
    OnboardMajorsResponse: {
      majors?: components['schemas']['LocalizedItemResponse'][];
    };
    BaseResponseOnboardFieldsResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['OnboardFieldsResponse'];
    };
    OnboardFieldsResponse: {
      fields?: components['schemas']['LocalizedItemResponse'][];
    };
    BaseResponseOnboardCountriesResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['OnboardCountriesResponse'];
    };
    OnboardCountriesResponse: {
      countries?: components['schemas']['LocalizedItemResponse'][];
    };
    BaseResponseMypageResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['MypageResponse'];
    };
    MypageResponse: {
      /**
       * @description 이름
       * @example 홍승원
       */
      name?: string;
      /** @description 프로필 사진 url */
      profileImageUrl?: string;
      /**
       * @description 목표 직무
       * @example Developer
       */
      targetJob?: string;
      /**
       * Format: date
       * @description 생년월일
       */
      birthDate?: string;
      /** @description 국가 */
      country?: string;
      /** @description 학위 */
      degree?: string;
      /** @description 대학 */
      university?: string;
      /**
       * @description 전공
       * @example Computer Science
       */
      primaryMajor?: string;
      /**
       * @description 부전공
       * @example Statistic
       */
      secondaryMajor?: string;
      /**
       * @description 비자 유형
       * @example D-2
       */
      visaType?: string;
      /**
       * Format: date
       * @description 비자 만료일
       */
      visaExpiredAt?: string;
      /**
       * @description 언어 수준
       * @enum {string}
       */
      languageLevel?:
        | 'LEVEL_1'
        | 'LEVEL_2'
        | 'LEVEL_3'
        | 'LEVEL_4'
        | 'LEVEL_5'
        | 'NOT_TAKEN';
      /** @description 영어 실력 */
      englishLevel?: string;
    };
    BaseResponseMemberInfoResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['MemberInfoResponse'];
    };
    /** @description 회원 정보 응답 */
    MemberInfoResponse: {
      /**
       * Format: int64
       * @description 회원 id
       * @example 1
       */
      memberId?: number;
      /**
       * @description 회원 이름
       * @example 홍길동
       */
      name?: string;
      /**
       * @description 회원 이메일
       * @example test@example.com
       */
      email?: string;
      /**
       * @description 프로필 이미지 URL
       * @example https://cdn.example.com/profile.png
       */
      profileImageUrl?: string;
      /**
       * Format: date
       * @description 생년월일
       * @example 2000-05-02
       */
      birthDate?: string;
      /** @description 거주 국가 */
      country?: string;
      /**
       * @description 주 전공
       * @example Computer Science
       */
      primaryMajor?: string;
      /**
       * @description 부 전공
       * @example Statistics
       */
      secondaryMajor?: string;
      /**
       * @description 타겟 직무
       * @example Backend Engineer
       */
      targetJob?: string;
      /**
       * @description 대학교
       * @example Seoul National University
       */
      university?: string;
      /**
       * Format: date
       * @description 졸업일
       * @example 2026-02-11
       */
      graduationDate?: string;
      /**
       * Format: date
       * @description 예상 졸업일
       * @example 2026-02-11
       */
      expectedGraduationDate?: string;
      /**
       * @description 언어 수준
       * @enum {string}
       */
      languageLevel?:
        | 'LEVEL_1'
        | 'LEVEL_2'
        | 'LEVEL_3'
        | 'LEVEL_4'
        | 'LEVEL_5'
        | 'NOT_TAKEN';
      /**
       * @description 학위
       * @example Bachelor
       */
      degree?: string;
      /**
       * @description 영어 수준
       * @example Upper Intermediate
       */
      englishLevel?: string;
      /**
       * @description 타겟 직무 스킬
       * @example Java, Spring
       */
      targetJobSkill?: string;
      /**
       * @description 비자 유형
       * @enum {string}
       */
      visaType?: 'D2' | 'D10' | 'E7';
    };
    BaseResponseMemberStatusResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['MemberStatusResponse'];
    };
    MemberStatusResponse: {
      /**
       * @description 비자 상태
       * @enum {string}
       */
      visaType?: 'D2' | 'D10' | 'E7';
      /**
       * Format: date
       * @description 비자 만료일
       */
      visaExpiredAt?: string;
      /**
       * Format: date
       * @description 졸업 예정일
       */
      expectedGraduationDate?: string;
      /**
       * Format: date
       * @description 졸업일
       */
      graduationDate?: string;
      /**
       * @description 온보딩 여부
       * @example true
       */
      onboardingRequired?: boolean;
    };
    BaseResponseJobPostingCrawlListResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['JobPostingCrawlListResponse'];
    };
    JobPostingCrawlListResponse: {
      crawlResponses?: components['schemas']['JobPostingCrawlResponse'][];
    };
    JobPostingCrawlResponse: {
      /**
       * @description 채용 공고 제목
       * @example D2, D10 Golf Caddy Training and Employment Linkage Program for International
       */
      postTitle?: string;
      /**
       * @description 회사명
       * @example 팀잡플로이
       */
      company?: string;
      /**
       * Format: date
       * @description 채용 공고 마감일
       * @example 2026-01-01
       */
      deadline?: string;
      /** @description 채용 공고 사이트 링크 */
      websiteUrl?: string;
      /** @description 공고 이미지 url */
      imageUrl?: string;
      /**
       * @description 비자 요구사항
       * @example D-2, D-10
       */
      preferredVisa?: string;
      /**
       * @description 언어 요구사항
       * @example you must prepare for TOPIK Level 4 to obtain F2R.
       */
      preferredLanguage?: string;
      /**
       * @description 근무 형태
       * @example Intern, Regular work
       */
      arrangement?: string;
      /**
       * @description 주소
       * @example Chungnam Asan-si, Gangwon Gangneung-si
       */
      address?: string;
    };
    ActionItemListResponse: {
      visaActionItems?: components['schemas']['ActionItemResponse'][];
      careerActionItems?: components['schemas']['ActionItemResponse'][];
    };
    /** @description Action Item 응답(Todo) */
    ActionItemResponse: {
      /**
       * Format: int64
       * @description Action Item id
       * @example 1
       */
      actionItemId?: number;
      /**
       * @description Action Item 제목
       * @example Prepare Resume
       */
      title?: string;
      /**
       * Format: date
       * @description Action Item 마감일
       * @example 2025-10-15
       */
      deadline?: string;
      /**
       * @description Action Item 완료 여부
       * @example false
       */
      completed?: boolean;
    };
    BaseResponseActionItemListResponse: {
      /**
       * Format: int32
       * @example 200
       */
      code?: number;
      message?: string;
      data?: components['schemas']['ActionItemListResponse'];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getMypage: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseMypageResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  updateMypage: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MypageRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  onboardMember: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MemberOnboardV2Request'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  uploadRequired: {
    parameters: {
      query: {
        requiredCategory: 'VISA' | 'CAREER';
      };
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'multipart/form-data': {
          /**
           * Format: binary
           * @description 업로드할 PDF 파일
           */
          file: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseVoid'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
      /** @description Method Not Allowed */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
    };
  };
  uploadPolicyFile: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'multipart/form-data': {
          /** @description 업로드할 PDF 파일 */
          files: string[];
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  uploadJobPosting: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['JobPostingEmbeddingRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  createPhaseActionTodo: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path: {
        phaseActionId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  agreeTerms: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MemberTermsRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  generateRoadmap: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  generateRoadmapForTest: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseRoadmapTestResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  onboardMember_1: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MemberOnboardRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getVisaInfo: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseOcrVisaResponse'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
      /** @description Method Not Allowed */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
    };
  };
  getPassportInfo: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'multipart/form-data': {
          /** Format: binary */
          file: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseOcrPassportResponse'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
      /** @description Method Not Allowed */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
    };
  };
  createJobPostingBookmark: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path: {
        jobPostingId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  recommendJobPostings: {
    parameters: {
      query?: {
        includeCompletedTodo?: boolean;
      };
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'multipart/form-data': {
          files?: string[];
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseJobPostingListResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  signOut: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  reissue: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseTokenResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  exchange: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TokenExchangeRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseTokenExchangeResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  toggleActionItemCompletion: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path: {
        actionItemId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getTerms: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseTermsResponse'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
      /** @description Method Not Allowed */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
    };
  };
  getPhaseList: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponsePhaseListResponse'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
      /** @description Method Not Allowed */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
    };
  };
  getRoadmapPhaseDetail: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path: {
        phaseId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseRoadmapPhaseDetailResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getHomePhaseDetail: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path: {
        phaseId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseHomePhaseDetailResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getAiGuide: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path: {
        phaseActionId: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseAiGuideResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getOnboardUniversities: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseOnboardUniversitiesResponse'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
      /** @description Method Not Allowed */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
    };
  };
  getOnboardMajors: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseOnboardMajorsResponse'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
      /** @description Method Not Allowed */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
    };
  };
  getOnboardFields: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseOnboardFieldsResponse'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
      /** @description Method Not Allowed */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
    };
  };
  getOnboardCountries: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseOnboardCountriesResponse'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
      /** @description Method Not Allowed */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
    };
  };
  getMemberInfo: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseMemberInfoResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  deleteMember: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseVoid'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getMemberStatus: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseMemberStatusResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  crawlJobPostings: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseJobPostingCrawlListResponse'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
      /** @description Method Not Allowed */
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseErrorResponse'];
        };
      };
    };
  };
  getJobPostingBookmarks: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseJobPostingListResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  getAllActionItems: {
    parameters: {
      query?: never;
      header?: {
        /** @description Preferred language code (e.g., en, ko, zh-CN, vi) */
        'X-Preferred-Language'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          '*/*': components['schemas']['BaseResponseActionItemListResponse'];
        };
      };
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      405: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
}
